server:
  servlet:
    context-path: /
  port: ${PORT:8080}

spring:
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

logging:
  level:
    root: INFO

services:
  auth-service:
    url: ${AUTH_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true