scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [
          'buterweb:8080',
          'buterauth:8080',
          'buterbilling:8080',
          'buterorder:8080'
      ]