server:
  servlet:
    context-path: /
  port: ${PORT:8080}

spring:
  application:
    name: BUTER IN KUBE
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    root=DEBUG

services:
  auth-service:
    url: ${AUTH_SERVICE_URL}
  order-service:
    url: ${ORDER_SERVICE_URL}
  billing-service:
    url: ${BILLING_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true